version: "3.9"
services:
  db:
    image: mysql:5.7
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress  # Replace with a strong password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress  # Replace with a strong password
    networks:
      - app-network
  wordpress:
    image: wordpress:latest
    volumes:
      - ./wordpress:/var/www/html
      - ./plugins:/var/www/html/wp-content/plugins  
    ports:
      - "8000:80"   
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress  
      WORDPRESS_DB_NAME: wordpress
    networks:
      - app-network
  nginx:
    build: ./nginx-conf  
    restart: unless-stopped
    ports:
      - "80:80"  
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
volumes:
  db_data:
networks:
  app-network:
